# Generated by Django 4.2.7 on 2025-04-18 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=100, unique=True, verbose_name='Трек-код')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('in_warehouse', 'Товар попал в склад'), ('shipped', 'Товар отправился'), ('in_almaty', 'Товар в Алматы'), ('in_aktobe', 'Товар в Актобе'), ('delivered', 'Товар передан клиенту')], default='in_warehouse', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Посылка',
                'verbose_name_plural': 'Посылки',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_warehouse', 'Товар попал в склад'), ('shipped', 'Товар отправился'), ('in_almaty', 'Товар в Алматы'), ('in_aktobe', 'Товар в Актобе'), ('delivered', 'Товар передан клиенту')], max_length=20, verbose_name='Статус')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Временная метка')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tracking.package', verbose_name='Посылка')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SavedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tracking.package', verbose_name='Посылка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_packages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохраненная посылка',
                'verbose_name_plural': 'Сохраненные посылки',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'package')},
            },
        ),
    ]
