# Generated by Django 4.2.9 on 2025-04-18 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Трек-код')),
                ('status', models.CharField(choices=[('1', 'Товар попал в склад'), ('2', 'Товар отправился'), ('3', 'Товар в алмате'), ('4', 'Товар в актобе'), ('5', 'Товар передан клиенту')], default='1', max_length=1, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Трек-код',
                'verbose_name_plural': 'Трек-коды',
            },
        ),
        migrations.CreateModel(
            name='UserTrackingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.trackingcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Трек-код пользователя',
                'verbose_name_plural': 'Трек-коды пользователей',
                'unique_together': {('user', 'tracking_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='savedpackage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='savedpackage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='package',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='SavedPackage',
        ),
        migrations.DeleteModel(
            name='StatusHistory',
        ),
    ]
